### PR TITLE
Added new article

### PR DESCRIPTION
**Pull request by nucliweb**

### CODE REVIEW

**Comment by danielguillan** [comment]
Thanks! Can you please change the author name to `Tim Kaedlec` and force-push again?

**Comment by nucliweb** [comment]
Done

**Comment by danielguillan** [comment]
Thanks!

**Comment by stefanjudis** [comment]
I think it's Tim Kadlec. -> https://timkadlec.com/ ;)

**Comment by danielguillan** [comment]
Ouch! My bad, I fixed the name and messed up with his last name. Thanks Stefan!

**Pull request merged**
