### PR TITLE
Added new video

### PR DESCRIPTION
**Pull request by nucliweb**

### CODE REVIEW

**Comment by danielguillan** [comment]
Great talk! Could you please move the resource to the Talks and Slides YAML file instead and force-push again?

Thanks a lot Joan!

**Comment by nucliweb** [comment]
Done

**Comment by danielguillan** [comment]
Thanks!

**Comment by danielguillan** [comment]
Whoops sorry, after double-checking I see that we already had that talk in the list: https://github.com/danielguillan/perf.rocks/blob/master/data/talks.yml#L263-L266

**Pull request merged**
